DROP TABLE if exists countries;

CREATE TABLE countries (
	country_name text NOT NULL,
	
     country_code text NULL,
     
    country_numeric_code int4 NULL,
	id int4,
    CONSTRAINT countries_pkey PRIMARY KEY (id),
	CONSTRAINT countries_unique UNIQUE (country_name)
);





insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, '', NULL, 206);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'State of Palestine', NULL, 196);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AD', 'Andorra', 20, 4);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Bolivia', NULL, 21);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Brunei', NULL, 25);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Congo, Democratic Republic of the', NULL, 39);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Congo, Republic of the', NULL, 40);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Czech Republic', NULL, 45);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'East Timor (Timor-Leste)', NULL, 50);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Iran', NULL, 78);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Korea, North', NULL, 89);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Korea, South', NULL, 90);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Kosovo', NULL, 91);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Laos', NULL, 94);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Macedonia', NULL, 103);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Micronesia', NULL, 114);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Moldova', NULL, 115);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Netherlands', NULL, 125);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Russia', NULL, 143);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Swaziland', NULL, 167);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Syria', NULL, 170);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Taiwan', NULL, 171);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Tanzania', NULL, 173);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Turkey', NULL, 179);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'United Kingdom', NULL, 185);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'United States', NULL, 186);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Vatican City', NULL, 190);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Venezuela', NULL, 191);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'Vietnam', NULL, 192);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AE', 'United Arab Emirates', 784, 184);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AF', 'Afghanistan', 4, 1);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AG', 'Antigua and Barbuda', 28, 6);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AI', 'Anguilla', 660, 208);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AL', 'Albania', 8, 2);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AM', 'Armenia', 51, 8);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AO', 'Angola', 24, 5);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AQ', 'Antarctica', 10, 212);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AR', 'Argentina', 32, 7);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AS', 'American Samoa', 16, 214);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AT', 'Austria', 40, 10);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AU', 'Australia', 36, 9);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AW', 'Aruba', 533, 217);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AX', 'Aland Islands', 248, 218);
insert into countries (country_code, country_name, country_numeric_code, id) values ('AZ', 'Azerbaijan', 31, 11);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BA', 'Bosnia and Herzegovina', 70, 22);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BB', 'Barbados', 52, 15);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BD', 'Bangladesh', 50, 14);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BE', 'Belgium', 56, 17);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BF', 'Burkina Faso', 854, 27);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BG', 'Bulgaria', 100, 26);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BH', 'Bahrain', 48, 13);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BI', 'Burundi', 108, 28);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BJ', 'Benin', 204, 19);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BL', 'Saint Barthelemy', 652, 229);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BM', 'Bermuda', 60, 230);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BN', 'Brunei Darussalam', 96, 231);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BO', 'Bolivia (Plurinational State of)', 68, 232);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BQ', 'Bonaire, Sint Eustatius and Saba', 535, 233);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BR', 'Brazil', 76, 24);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BS', 'Bahamas', 44, 12);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BT', 'Bhutan', 64, 20);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BV', 'Bouvet Island', 74, 237);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BW', 'Botswana', 72, 23);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BY', 'Belarus', 112, 16);
insert into countries (country_code, country_name, country_numeric_code, id) values ('BZ', 'Belize', 84, 18);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CA', 'Canada', 124, 32);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CC', 'Cocos (Keeling) Islands', 166, 242);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CD', 'Congo (the Democratic Republic of the)', 180, 243);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CF', 'Central African Republic', 140, 33);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CG', 'Congo', 178, 245);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CH', 'Switzerland', 756, 169);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CI', 'Cote d''Ivoire', 384, 247);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CK', 'Cook Islands', 184, 248);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CL', 'Chile', 152, 35);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CM', 'Cameroon', 120, 31);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CN', 'China', 156, 36);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CO', 'Colombia', 170, 37);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CR', 'Costa Rica', 188, 41);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CU', 'Cuba', 192, 43);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CV', 'Cabo Verde', 132, 29);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CW', 'Curacao', 531, 256);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CX', 'Christmas Island', 162, 257);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CY', 'Cyprus', 196, 44);
insert into countries (country_code, country_name, country_numeric_code, id) values ('CZ', 'Czechia', 203, 259);
insert into countries (country_code, country_name, country_numeric_code, id) values ('DE', 'Germany', 276, 64);
insert into countries (country_code, country_name, country_numeric_code, id) values ('DJ', 'Djibouti', 262, 47);
insert into countries (country_code, country_name, country_numeric_code, id) values ('DK', 'Denmark', 208, 46);
insert into countries (country_code, country_name, country_numeric_code, id) values ('DM', 'Dominica', 212, 48);
insert into countries (country_code, country_name, country_numeric_code, id) values ('DO', 'Dominican Republic', 214, 49);
insert into countries (country_code, country_name, country_numeric_code, id) values ('DZ', 'Algeria', 12, 3);
insert into countries (country_code, country_name, country_numeric_code, id) values ('EC', 'Ecuador', 218, 51);
insert into countries (country_code, country_name, country_numeric_code, id) values ('EE', 'Estonia', 233, 56);
insert into countries (country_code, country_name, country_numeric_code, id) values ('EG', 'Egypt', 818, 52);
insert into countries (country_code, country_name, country_numeric_code, id) values ('EH', 'Western Sahara', 732, 269);
insert into countries (country_code, country_name, country_numeric_code, id) values ('ER', 'Eritrea', 232, 55);
insert into countries (country_code, country_name, country_numeric_code, id) values ('ES', 'Spain', 724, 163);
insert into countries (country_code, country_name, country_numeric_code, id) values ('ET', 'Ethiopia', 231, 57);
insert into countries (country_code, country_name, country_numeric_code, id) values ('FI', 'Finland', 246, 59);
insert into countries (country_code, country_name, country_numeric_code, id) values ('FJ', 'Fiji', 242, 58);
insert into countries (country_code, country_name, country_numeric_code, id) values ('FK', 'Falkland Islands [Malvinas]', 238, 275);
insert into countries (country_code, country_name, country_numeric_code, id) values ('FM', 'Micronesia (Federated States of)', 583, 276);
insert into countries (country_code, country_name, country_numeric_code, id) values ('FO', 'Faroe Islands', 234, 277);
insert into countries (country_code, country_name, country_numeric_code, id) values ('FR', 'France', 250, 60);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GA', 'Gabon', 266, 61);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GB', 'United Kingdom of Great Britain and Northern Ireland', 826, 280);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GD', 'Grenada', 308, 67);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GE', 'Georgia', 268, 63);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GF', 'French Guiana', 254, 283);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GG', 'Guernsey', 831, 284);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GH', 'Ghana', 288, 65);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GI', 'Gibraltar', 292, 286);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'europe', NULL, 200);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GL', 'Greenland', 304, 287);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GM', 'Gambia', 270, 62);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'new_test1', NULL, 197);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'new_test2', NULL, 198);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'new_test3', NULL, 199);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GN', 'Guinea', 324, 69);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'new_test4', NULL, 201);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GP', 'Guadeloupe', 312, 290);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'new_test5', NULL, 203);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GQ', 'Equatorial Guinea', 226, 54);
insert into countries (country_code, country_name, country_numeric_code, id) values (NULL, 'new_co', NULL, 205);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GR', 'Greece', 300, 66);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GS', 'South Georgia and the South Sandwich Islands', 239, 293);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GT', 'Guatemala', 320, 68);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GU', 'Guam', 316, 295);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GW', 'Guinea-Bissau', 624, 70);
insert into countries (country_code, country_name, country_numeric_code, id) values ('GY', 'Guyana', 328, 71);
insert into countries (country_code, country_name, country_numeric_code, id) values ('HK', 'Hong Kong', 344, 298);
insert into countries (country_code, country_name, country_numeric_code, id) values ('HM', 'Heard Island and McDonald Islands', 334, 299);
insert into countries (country_code, country_name, country_numeric_code, id) values ('HN', 'Honduras', 340, 73);
insert into countries (country_code, country_name, country_numeric_code, id) values ('HR', 'Croatia', 191, 42);
insert into countries (country_code, country_name, country_numeric_code, id) values ('HT', 'Haiti', 332, 72);
insert into countries (country_code, country_name, country_numeric_code, id) values ('HU', 'Hungary', 348, 74);
insert into countries (country_code, country_name, country_numeric_code, id) values ('ID', 'Indonesia', 360, 77);
insert into countries (country_code, country_name, country_numeric_code, id) values ('IE', 'Ireland', 372, 80);
insert into countries (country_code, country_name, country_numeric_code, id) values ('IL', 'Israel', 376, 81);
insert into countries (country_code, country_name, country_numeric_code, id) values ('IM', 'Isle of Man', 833, 308);
insert into countries (country_code, country_name, country_numeric_code, id) values ('IN', 'India', 356, 76);
insert into countries (country_code, country_name, country_numeric_code, id) values ('IO', 'British Indian Ocean Territory', 86, 310);
insert into countries (country_code, country_name, country_numeric_code, id) values ('IQ', 'Iraq', 368, 79);
insert into countries (country_code, country_name, country_numeric_code, id) values ('IR', 'Iran (Islamic Republic of)', 364, 312);
insert into countries (country_code, country_name, country_numeric_code, id) values ('IS', 'Iceland', 352, 75);
insert into countries (country_code, country_name, country_numeric_code, id) values ('IT', 'Italy', 380, 82);
insert into countries (country_code, country_name, country_numeric_code, id) values ('JE', 'Jersey', 832, 315);
insert into countries (country_code, country_name, country_numeric_code, id) values ('JM', 'Jamaica', 388, 83);
insert into countries (country_code, country_name, country_numeric_code, id) values ('JO', 'Jordan', 400, 85);
insert into countries (country_code, country_name, country_numeric_code, id) values ('JP', 'Japan', 392, 84);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KE', 'Kenya', 404, 87);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KG', 'Kyrgyzstan', 417, 93);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KH', 'Cambodia', 116, 30);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KI', 'Kiribati', 296, 88);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KM', 'Comoros', 174, 38);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KN', 'Saint Kitts and Nevis', 659, 145);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KP', 'Korea (the Democratic People''s Republic of)', 408, 325);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KR', 'Korea (the Republic of)', 410, 326);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KW', 'Kuwait', 414, 92);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KY', 'Cayman Islands', 136, 328);
insert into countries (country_code, country_name, country_numeric_code, id) values ('KZ', 'Kazakhstan', 398, 86);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LA', 'Lao People''s Democratic Republic', 418, 330);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LB', 'Lebanon', 422, 96);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LC', 'Saint Lucia', 662, 146);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LI', 'Liechtenstein', 438, 100);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LK', 'Sri Lanka', 144, 164);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LR', 'Liberia', 430, 98);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LS', 'Lesotho', 426, 97);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LT', 'Lithuania', 440, 101);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LU', 'Luxembourg', 442, 102);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LV', 'Latvia', 428, 95);
insert into countries (country_code, country_name, country_numeric_code, id) values ('LY', 'Libya', 434, 99);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MA', 'Morocco', 504, 119);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MC', 'Monaco', 492, 116);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MD', 'Moldova (the Republic of)', 498, 343);
insert into countries (country_code, country_name, country_numeric_code, id) values ('ME', 'Montenegro', 499, 118);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MF', 'Saint Martin (French part)', 663, 345);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MG', 'Madagascar', 450, 104);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MH', 'Marshall Islands', 584, 110);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MK', 'North Macedonia', 807, 348);
insert into countries (country_code, country_name, country_numeric_code, id) values ('ML', 'Mali', 466, 108);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MM', 'Myanmar', 104, 121);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MN', 'Mongolia', 496, 117);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MO', 'Macao', 446, 352);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MP', 'Northern Mariana Islands', 580, 353);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MQ', 'Martinique', 474, 354);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MR', 'Mauritania', 478, 111);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MS', 'Montserrat', 500, 356);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MT', 'Malta', 470, 109);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MU', 'Mauritius', 480, 112);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MV', 'Maldives', 462, 107);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MW', 'Malawi', 454, 105);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MX', 'Mexico', 484, 113);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MY', 'Malaysia', 458, 106);
insert into countries (country_code, country_name, country_numeric_code, id) values ('MZ', 'Mozambique', 508, 120);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NA', 'Namibia', 516, 122);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NC', 'New Caledonia', 540, 365);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NE', 'Niger', 562, 128);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NF', 'Norfolk Island', 574, 367);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NG', 'Nigeria', 566, 129);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NI', 'Nicaragua', 558, 127);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NL', 'Netherlands (Kingdom of the)', 528, 370);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NO', 'Norway', 578, 130);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NP', 'Nepal', 524, 124);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NR', 'Nauru', 520, 123);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NU', 'Niue', 570, 374);
insert into countries (country_code, country_name, country_numeric_code, id) values ('NZ', 'New Zealand', 554, 126);
insert into countries (country_code, country_name, country_numeric_code, id) values ('OM', 'Oman', 512, 131);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PA', 'Panama', 591, 134);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PE', 'Peru', 604, 137);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PF', 'French Polynesia', 258, 379);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PG', 'Papua New Guinea', 598, 135);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PH', 'Philippines', 608, 138);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PK', 'Pakistan', 586, 132);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PL', 'Poland', 616, 139);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PM', 'Saint Pierre and Miquelon', 666, 384);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PN', 'Pitcairn', 612, 385);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PR', 'Puerto Rico', 630, 386);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PS', 'Palestine, State of', 275, 387);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PT', 'Portugal', 620, 140);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PW', 'Palau', 585, 133);
insert into countries (country_code, country_name, country_numeric_code, id) values ('PY', 'Paraguay', 600, 136);
insert into countries (country_code, country_name, country_numeric_code, id) values ('QA', 'Qatar', 634, 141);
insert into countries (country_code, country_name, country_numeric_code, id) values ('RE', 'Reunion', 638, 392);
insert into countries (country_code, country_name, country_numeric_code, id) values ('RO', 'Romania', 642, 142);
insert into countries (country_code, country_name, country_numeric_code, id) values ('RS', 'Serbia', 688, 153);
insert into countries (country_code, country_name, country_numeric_code, id) values ('RU', 'Russian Federation', 643, 395);
insert into countries (country_code, country_name, country_numeric_code, id) values ('RW', 'Rwanda', 646, 144);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SA', 'Saudi Arabia', 682, 151);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SB', 'Solomon Islands', 90, 159);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SC', 'Seychelles', 690, 154);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SD', 'Sudan', 729, 165);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SE', 'Sweden', 752, 168);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SG', 'Singapore', 702, 156);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 654, 403);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SI', 'Slovenia', 705, 158);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SJ', 'Svalbard and Jan Mayen', 744, 407);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SK', 'Slovakia', 703, 157);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SL', 'Sierra Leone', 694, 155);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SM', 'San Marino', 674, 149);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SN', 'Senegal', 686, 152);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SO', 'Somalia', 706, 160);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SR', 'Suriname', 740, 166);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SS', 'South Sudan', 728, 162);
insert into countries (country_code, country_name, country_numeric_code, id) values ('ST', 'Sao Tome and Principe', 678, 150);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SV', 'El Salvador', 222, 53);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SX', 'Sint Maarten (Dutch part)', 534, 417);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SY', 'Syrian Arab Republic', 760, 418);
insert into countries (country_code, country_name, country_numeric_code, id) values ('SZ', 'Eswatini', 748, 419);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TC', 'Turks and Caicos Islands', 796, 420);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TD', 'Chad', 148, 34);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TF', 'French Southern Territories', 260, 422);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TG', 'Togo', 768, 175);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TH', 'Thailand', 764, 174);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TJ', 'Tajikistan', 762, 172);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TK', 'Tokelau', 772, 426);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TL', 'Timor-Leste', 626, 427);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TM', 'Turkmenistan', 795, 180);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TN', 'Tunisia', 788, 178);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TO', 'Tonga', 776, 176);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TR', 'Turkiye', 792, 431);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TT', 'Trinidad and Tobago', 780, 177);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TV', 'Tuvalu', 798, 181);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TW', 'Taiwan (Province of China)', 158, 434);
insert into countries (country_code, country_name, country_numeric_code, id) values ('TZ', 'Tanzania, the United Republic of', 834, 435);
insert into countries (country_code, country_name, country_numeric_code, id) values ('UA', 'Ukraine', 804, 183);
insert into countries (country_code, country_name, country_numeric_code, id) values ('UG', 'Uganda', 800, 182);
insert into countries (country_code, country_name, country_numeric_code, id) values ('UM', 'United States Minor Outlying Islands', 581, 438);
insert into countries (country_code, country_name, country_numeric_code, id) values ('US', 'United States of America', 840, 439);
insert into countries (country_code, country_name, country_numeric_code, id) values ('UY', 'Uruguay', 858, 187);
insert into countries (country_code, country_name, country_numeric_code, id) values ('UZ', 'Uzbekistan', 860, 188);
insert into countries (country_code, country_name, country_numeric_code, id) values ('VA', 'Holy See', 336, 442);
insert into countries (country_code, country_name, country_numeric_code, id) values ('VC', 'Saint Vincent and the Grenadines', 670, 147);
insert into countries (country_code, country_name, country_numeric_code, id) values ('VE', 'Venezuela (Bolivarian Republic of)', 862, 444);
insert into countries (country_code, country_name, country_numeric_code, id) values ('VG', 'Virgin Islands (British)', 92, 445);
insert into countries (country_code, country_name, country_numeric_code, id) values ('VI', 'Virgin Islands (U.S.)', 850, 446);
insert into countries (country_code, country_name, country_numeric_code, id) values ('VN', 'Viet Nam', 704, 447);
insert into countries (country_code, country_name, country_numeric_code, id) values ('VU', 'Vanuatu', 548, 189);
insert into countries (country_code, country_name, country_numeric_code, id) values ('WF', 'Wallis and Futuna', 876, 449);
insert into countries (country_code, country_name, country_numeric_code, id) values ('WS', 'Samoa', 882, 148);
insert into countries (country_code, country_name, country_numeric_code, id) values ('YE', 'Yemen', 887, 193);
insert into countries (country_code, country_name, country_numeric_code, id) values ('YT', 'Mayotte', 175, 452);
insert into countries (country_code, country_name, country_numeric_code, id) values ('ZA', 'South Africa', 710, 161);
insert into countries (country_code, country_name, country_numeric_code, id) values ('ZM', 'Zambia', 894, 194);
insert into countries (country_code, country_name, country_numeric_code, id) values ('ZW', 'Zimbabwe', 716, 195);